openapi: 3.0.3
info:
  title: 'Virtual file system API Documentation'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
tags:
  -
    name: Endpoints
    description: ''
paths:
  /api/folders:
    get:
      summary: ''
      operationId: getApiFolders
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    post:
      summary: ''
      operationId: postApiFolders
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must match the regex /^[a-zA-Z0-9\s\p{Pd}_.]+$/. Must not be greater than 255 characters.'
                  example: b
                  nullable: false
              required:
                - name
      security: []
  '/api/folders/{id}':
    patch:
      summary: ''
      operationId: patchApiFoldersId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must match the regex /^[a-zA-Z0-9\s\p{Pd}_.]+$/. Must not be greater than 255 characters.'
                  example: b
                  nullable: false
              required:
                - name
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the folder.'
        example: 1
        required: true
        schema:
          type: integer
  '/api/folders/{folder_id}':
    delete:
      summary: ''
      operationId: deleteApiFoldersFolder_id
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: folder_id
        description: 'The ID of the folder.'
        example: 1
        required: true
        schema:
          type: integer
  /api/files:
    post:
      summary: ''
      operationId: postApiFiles
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Must match the regex /^[a-zA-Z0-9\s\p{Pd}_.]+$/. Must not be greater than 255 characters.'
                  example: b
                  nullable: false
                content:
                  type: string
                  description: 'Must not be greater than 10000 characters.'
                  example: 'n'
                  nullable: true
              required:
                - name
      security: []
  '/api/files/{id}':
    patch:
      summary: ''
      operationId: patchApiFilesId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the file.'
        example: 1
        required: true
        schema:
          type: integer
  '/api/files/{file_id}':
    delete:
      summary: ''
      operationId: deleteApiFilesFile_id
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: file_id
        description: 'The ID of the file.'
        example: 1
        required: true
        schema:
          type: integer
  /api/user:
    get:
      summary: ''
      operationId: getApiUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
